volumes:
  pg_data:

services:
  db:
    build: .
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data